SET ECHO ON
 
CREATE TABLE DBSNMP.DDL_LOG
(
PDB            VARCHAR2(30), 
DDL_DATE       TIMESTAMP,          
DDL_TYPE       VARCHAR2(30),  
DB_USER        VARCHAR2(30),   
OS_USER        VARCHAR2(300), 
OBJ_ID         NUMBER,        
OBJ_TYPE       VARCHAR2(18),  
OBJ_OWNER      VARCHAR2(30),  
OBJ_NAME       VARCHAR2(150), 
OBJ_VERSION    NUMBER, 
SQL_ID         VARCHAR2(20),  
SQL_TEXT       CLOB,          
OBJ_BKP        CLOB,		  
TERMINAL       VARCHAR2(300), 
PROGRAM        VARCHAR2(300), 
IPADRESS       VARCHAR2(46),  
ACTION	       VARCHAR2(300),
MODULE         VARCHAR2(300),
CLIENT_INFO    VARCHAR2(300),
obj_hash       VARCHAR2(64)
) TABLESPACE USERS
/
CREATE OR REPLACE PUBLIC SYNONYM DDL_LOG FOR DBSNMP.DDL_LOG; 
CREATE INDEX DBSNMP.DDL_LOG_IDX01 ON DDL_LOG (DDL_DATE) TABLESPACE USERS;



CREATE TABLE DBSNMP.DDL_LOG_PROGRAM_EXCEPTION
   (    DATE_INC DATE,
        PROGRAM VARCHAR2(300)
   ) TABLESPACE USERS
/
CREATE OR REPLACE PUBLIC SYNONYM DDL_LOG_PROGRAM_EXCEPTION FOR DBSNMP.DDL_LOG_PROGRAM_EXCEPTION;
CREATE unique INDEX  DBSNMP.DDL_LOG_PROG_EXCEPTION_IDX01 ON  DDL_LOG_PROGRAM_EXCEPTION (PROGRAM) TABLESPACE USERS;


CREATE TABLE DBSNMP.DDL_LOG_PROGRAM_USER_EXCEPTION
   (    DATE_INC DATE,
        PROGRAM VARCHAR2(300),
		DB_USER VARCHAR2(30)
) TABLESPACE USERS
/
CREATE OR REPLACE PUBLIC SYNONYM DDL_LOG_PROGRAM_USER_EXCEPTION FOR DBSNMP.DDL_LOG_PROGRAM_USER_EXCEPTION;
CREATE unique INDEX  DBSNMP.DDL_LOG_PROGRAM_USER_EXCEPTION_IDX01 ON  DDL_LOG_PROGRAM_USER_EXCEPTION (PROGRAM,DB_USER) TABLESPACE USERS;





delete DDL_LOG_PROGRAM_EXCEPTION
/
commit
/
begin execute immediate 'insert into  DDL_LOG_PROGRAM_EXCEPTION select SYSDATE, ''PAYTRUE.PAYSTUDIO.REQUEST'' from dual'; commit; exception when others then null; end; 
/
BEGIN EXECUTE IMMEDIATE 'INSERT INTO  DDL_LOG_PROGRAM_EXCEPTION SELECT SYSDATE, ''PAYTRUE.PAYSTUDIO.REQUESTDISPATCHER.RUNNER.SERVI'' FROM DUAL'; COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'INSERT INTO  DDL_LOG_PROGRAM_EXCEPTION SELECT SYSDATE, ''BATCHEXECUTOR.EXE'' FROM DUAL'; COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
select * from DDL_LOG_PROGRAM_EXCEPTION
/
delete DDL_LOG where upper(program) in ('BATCHEXECUTOR.EXE', 'PAYTRUE.PAYSTUDIO.REQUESTDISPATCHER.RUNNER.SERVI', 'PAYTRUE.PAYSTUDIO.REQUEST' )
/
commit
/
select * from DDL_LOG_PROGRAM_EXCEPTION
/

BEGIN EXECUTE IMMEDIATE 'INSERT INTO  DDL_LOG_PROGRAM_USER_EXCEPTION SELECT SYSDATE, ''SQLPLUS.EXE'', ''RSE'' FROM DUAL'; COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'INSERT INTO  DDL_LOG_PROGRAM_USER_EXCEPTION SELECT SYSDATE, ''SQLPLUS.EXE'', ''JOBS_CONTROLM'' FROM DUAL'; COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
SET ECHO OFF
